# Homebrew formula for labelize
# Install: brew install GOODBOY008/homebrew-labelize/labelize
# Or: brew tap GOODBOY008/homebrew-labelize && brew install labelize
#
# This formula is auto-generated by the release workflow.
# Manual formula template — update URLs and SHA256 sums on each release.

class Labelize < Formula
  desc "Turn ZPL/EPL into pixels — label rendering, simplified."
  homepage "https://github.com/GOODBOY008/labelize"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/GOODBOY008/labelize/releases/download/v0.1.0/labelize-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/GOODBOY008/labelize/releases/download/v0.1.0/labelize-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    url "https://github.com/GOODBOY008/labelize/releases/download/v0.1.0/labelize-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "PLACEHOLDER"
  end

  def install
    bin.install "labelize"
  end

  test do
    assert_match "labelize", shell_output("#{bin}/labelize --version")
  end
end
